### ISSUE TITLE
Tela: gerenciamento de permissões

### ISSUE THREAD

**Issue by Pr3d4dor** [C3DSU/e-DefPR#277]
Implementar tela de gerenciamento de permissões de usuário que deve permitir escolher a role de um usuário e também escolher as permissões específicas do mesmo.

Por exemplo, ao escolher a role estagiário administrativo para um usuário, a tela automaticamente deve preencher todas as permissões, porém será possível desmarcar/marcar outras permissões além das padrões dessa role.

requires #374
requires #372
requires #436

**Comment by HigorG** [comment]
requires #436
