### ISSUE TITLE
Corrigir acesso a rotas inexistentes

### ISSUE THREAD

**Issue by EnViKeyy** [C3DSU/e-DefPR#317]
É possível fazer um GET da permissão 02 com mais de uma url.

http://localhost:8000/api/role/7
http://localhost:8000/api/role/7ghs

As duas rotas funcionam

**Comment by Pr3d4dor** [comment]
Isso se deve ao fato de que no momento de fazer a consulta no BD, o PHP realiza o cast de string para integer. 

Portanto a string "12asd" é convertida para o integer 12.

Verificar se é possível fazer alguma correção.
