### ISSUE TITLE
Cadastro Funcionário espera Json em birth_place

### ISSUE THREAD

**Issue by agueths** [C3DSU/e-DefPR#334]
Quando tento enviar o create, ele da esse retorno:

```{"message":"SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: \"not a JSON text, may need CAST\" at position 0 in value for column 'users.birth_place'. (SQL: insert into `users` (`name`, `email`, `password`, `cpf`, `birth_date`, `birth_place`, `rg`, `rg_issuer`, `gender`, `marital_status`, `addresses`, `note`, `profession`, `must_change_password`, `updated_at`, `created_at`) values (TEste 1, nao@tem.com, $2y$10$9SVTTtd5bvXoecrvJ\/Sufe6y0Dhx9ZLnCD9G9pv7NhVoXsmZgHpdW, 00000000000, 1978-09-06 12:45:20, 4109401, 123123123, sesp pr, M, solteiro, [{\"cep\":\"85000100\",\"number\":\"0\",\"state\":41,\"city\":4109401,\"neighbourhood\":\"Centro\",\"street\":\"dos tolos\"}], , Programador, 1, 2018-09-06 12:45:20, 2018-09-06 12:45:20))"}```
required by #302

**Comment by paulopieczarka** [comment]
![image](https://user-images.githubusercontent.com/14002748/45158723-40440380-b1bb-11e8-93dc-0b091ec8c605.png)

**Comment by Pr3d4dor** [comment]
Verificar como foi feito na migration de Assistido e corrigir.
