### ISSUE TITLE
Readequar Documentação

### ISSUE THREAD

**Issue by hdoidao** [C3DSU/e-DefPR#335]
Readequar documentação do Drive de equipe para futuro registro do software

**Comment by EnViKeyy** [comment]
na figura 4.2, caso de uso abrir processo também pode ser feito pelo assessor jurídico, em triagem inicial também pode ser feito pelo assessor jurídico e estagiário de direito, no caso de uso cadastrar documentos não pode ser feito pelo estagiário de ensino médio.

**Comment by EnViKeyy** [comment]
na figura 4.1, o caso de uso gerenciar assistido só pode ser feito pelo defensor publico

**Comment by EnViKeyy** [comment]
na figura 4.1, remover o caso de uso gerar relatório assistido

**Comment by EnViKeyy** [comment]
na figura 4.1, o caso de uso gerar relatório de atividades não pode ser feito pelo estagiário de ensino médio, mas pode ser feito pelo assessor jurídico, assistente social e psicólogo

**Comment by EnViKeyy** [comment]
na figura 4.1, o caso de uso registrar atividade pode ser feito por todos os papeis
